---
Name: anytech-googlereviews
After:
- '#coreconfig'
- '#elementalconfig'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
  - anytech\googlereviews\Extensions\SiteConfigGoogleReviewsExtension

SilverStripe\Dev\CronTask\CronTaskController:
  tasks:
  - anytech\googlereviews\Tasks\GoogleReviewsSyncTask
